import fs from 'fs';
import { encodeWorkoutAsFit } from '../src/fit';
import { WorkoutSession } from '../src/types';

const session: WorkoutSession = {
  id: 'test-session-123',
  startedAt: Date.now() - 3600000, // 1 hour ago
  completedAt: Date.now(),
  exercises: [
    {
      id: 'ex-1',
      exerciseKey: 'bench_press',
      name: 'Bench Press',
      sets: [
        { id: 'set-1', weight: 135, reps: 10, completedAt: Date.now() - 3000000 },
        { id: 'set-2', weight: 185, reps: 8, completedAt: Date.now() - 2500000 },
        { id: 'set-3', weight: 225, reps: 5, completedAt: Date.now() - 2000000 },
      ]
    },
    {
      id: 'ex-2',
      exerciseKey: 'squat',
      name: 'Squat',
      sets: [
        { id: 'set-4', weight: 225, reps: 5, completedAt: Date.now() - 1000000 },
        { id: 'set-5', weight: 315, reps: 3, completedAt: Date.now() - 500000 },
      ]
    }
  ],
  notes: 'Test workout generated by agent'
};

const bytes = encodeWorkoutAsFit(session, { weightUnit: 'lb' });
fs.writeFileSync('test_workout.fit', Buffer.from(bytes));
console.log('Successfully generated test_workout.fit');
