import type { DungeonMusicMode } from './dungeonAudio';

export type DoctrineQuestion = {
  id: string;
  bossTheme: DungeonMusicMode | 'general';
  prompt: string;
  options: string[];
  answer: number;
  lesson: string;
};

export const DOCTRINE_QUESTIONS: DoctrineQuestion[] = [
  {
    id: 'failure_compounds', bossTheme: 'boss',
    prompt: 'Heavy barbell compound is already moving slow. What is the highest-signal hypertrophy call?',
    options: ['Grind every set to failure because failure is always superior.', 'Keep 1-3 reps in reserve, push closer mainly on safer isolation/last sets.', 'Cut ROM short so fatigue stays low.'],
    answer: 1,
    lesson: 'Failure is not magic; close proximity matters, but compounds punish sloppy fatigue. Save true failure for safer contexts.',
  },
  {
    id: 'rest_intervals', bossTheme: 'boss',
    prompt: 'Your next boss set needs high output. What rest choice best protects performance?',
    options: ['Rest only 20 seconds to maximize burn.', 'Use enough rest to repeat quality work; short rest is not automatically better for growth.', 'Skip rest entirely if music is hype.'],
    answer: 1,
    lesson: 'Recent rest-interval reviews do not support “shorter is always better”; quality volume still rules.',
  },
  {
    id: 'volume_recovery', bossTheme: 'general',
    prompt: 'You are sore, performance is dropping, and joints feel cooked. Best progression decision?',
    options: ['Add sets anyway because more volume always scales linearly.', 'Hold or reduce volume until performance/recovery returns, then progress.', 'Max out to test character.'],
    answer: 1,
    lesson: 'Volume has a dose response only inside recoverable limits. Past that, fatigue steals adaptation.',
  },
  {
    id: 'lengthened_partials', bossTheme: 'battle',
    prompt: 'For hypertrophy, where are partial reps most defensible if you use them?',
    options: ['Only the shortened/easy lockout range.', 'The lengthened/challenging range, usually as a tool rather than a religion.', 'Any random half rep as long as it burns.'],
    answer: 1,
    lesson: 'Lengthened-position loading appears promising; shortened partials are usually the weaker bargain.',
  },
  {
    id: 'specificity_strength', bossTheme: 'boss',
    prompt: 'You want a stronger 1RM squat. What choice best respects specificity?',
    options: ['Never lift heavy; only 30-rep pump sets.', 'Include practice with heavier loads and skillful execution while managing fatigue.', 'Change exercises every session so the body stays confused.'],
    answer: 1,
    lesson: 'Hypertrophy can support strength, but maximal strength also needs heavy, specific, technically stable practice.',
  },
  {
    id: 'rir_autoregulation', bossTheme: 'general',
    prompt: 'Warmups feel unexpectedly heavy today. Smart autoregulated move?',
    options: ['Adjust load/sets to keep target RIR and technique quality.', 'Ignore readiness; the spreadsheet is sacred.', 'Double caffeine and attempt a PR.'],
    answer: 0,
    lesson: 'Autoregulation exists because daily strength fluctuates. The target stimulus matters more than ego load.',
  },
  {
    id: 'exercise_selection', bossTheme: 'battle',
    prompt: 'A muscle is the goal, but joints hate the movement. Best advanced substitution logic?',
    options: ['Keep the painful lift because “optimal” is always mandatory.', 'Choose a stable movement that trains the target hard through useful ROM with less joint cost.', 'Remove all hard sets forever.'],
    answer: 1,
    lesson: 'Stimulus-to-fatigue and adherence matter. A slightly less famous lift you can load safely often wins.',
  },
  {
    id: 'deload_signal', bossTheme: 'boss',
    prompt: 'Boss aura: sleep down, motivation low, loads regressing. Best mesocycle call?',
    options: ['Deload/reduce fatigue, then rebuild.', 'Add forced reps on every set.', 'Switch to only one-rep maxes until morale improves.'],
    answer: 0,
    lesson: 'Accumulated fatigue can mask fitness. Strategic unloading is not weakness; it is how the next wave gets teeth.',
  },
  {
    id: 'protein_basics', bossTheme: 'general',
    prompt: 'The Protein Moon demands a recovery offering. Most defensible baseline?',
    options: ['Protein distribution and adequate daily intake support adaptation.', 'Protein timing is everything; daily intake barely matters.', 'Supplements replace training quality.'],
    answer: 0,
    lesson: 'Nutrition supports the signal; it does not replace progressive training, sleep, and enough protein across the day.',
  },
  {
    id: 'novelty_trap', bossTheme: 'shop',
    prompt: 'New exercise looks cool but you cannot track progression. Best call?',
    options: ['Rotate everything constantly.', 'Use novelty sparingly; keep enough stable lifts to measure overload.', 'Only do exercises that trend on social media.'],
    answer: 1,
    lesson: 'Variation is useful when it serves the plan. Too much novelty hides whether you are actually progressing.',
  },
  {
    id: 'warmup_logic', bossTheme: 'general',
    prompt: 'Before a heavy boss set, what warmup strategy is cleanest?',
    options: ['Fatigue yourself with many hard warmup sets.', 'Ramp gradually with low-fatigue practice sets that prepare the target load.', 'Skip warmups to conserve mana.'],
    answer: 1,
    lesson: 'Warmups should increase readiness without spending the work capacity reserved for the hard sets.',
  },
  {
    id: 'technique_failure', bossTheme: 'boss',
    prompt: 'Rep speed collapses and technique changes. What does the doctrine say?',
    options: ['Technique failure is a valid stop even if the muscle could flail more.', 'Keep going until the bar pins you.', 'Count assisted contortions as clean reps.'],
    answer: 0,
    lesson: 'A set can be over when the target stimulus turns into compensation and risk.',
  },

  {
    id: 'weekly_set_ceiling', bossTheme: 'general',
    prompt: 'A lifter adds sets every week, but target muscle performance is falling. What is the high-level diagnosis?',
    options: ['They probably crossed their recoverable volume ceiling.', 'They need more novelty immediately.', 'They should remove all rest days.'],
    answer: 0,
    lesson: 'Volume is a tool, not a scoreboard. Effective volume lives under the lifter’s recovery ceiling.',
  },
  {
    id: 'long_muscle_lengths', bossTheme: 'battle',
    prompt: 'A boss offers either deep controlled leg curls or short-range top-half reps. Hypertrophy-biased choice?',
    options: ['Use the deep controlled work if joints tolerate it.', 'Only chase the easiest shortened range.', 'Never train hamstrings directly.'],
    answer: 0,
    lesson: 'Training at longer muscle lengths is often a strong hypertrophy bet when execution and tolerance are good.',
  },
  {
    id: 'strength_peaking', bossTheme: 'boss',
    prompt: 'Two weeks from a max test, fatigue is high but strength is present. Best peaking move?',
    options: ['Taper some volume while keeping enough intensity/skill practice.', 'Add brutal drop sets daily.', 'Switch to only machines until test day.'],
    answer: 0,
    lesson: 'Peaking usually manages fatigue down while preserving neural/technical readiness.',
  },
  {
    id: 'novice_vs_advanced', bossTheme: 'general',
    prompt: 'Why can an advanced lifter need more careful progression than a novice?',
    options: ['Their margin between useful stress and excess fatigue is often narrower.', 'Advanced lifters cannot gain muscle.', 'Novices need periodization tattoos first.'],
    answer: 0,
    lesson: 'As adaptation slows, precision matters more: exercise selection, volume, proximity, and recovery all tighten.',
  },
  {
    id: 'pain_vs_effort', bossTheme: 'battle',
    prompt: 'A set is hard and burning, but joint pain is sharp and changing mechanics. What is the correct distinction?',
    options: ['Pain and productive effort are not the same signal.', 'Sharp joint pain proves the set is anabolic.', 'Ignore all sensation forever.'],
    answer: 0,
    lesson: 'Hard muscular effort can be useful. Sharp joint pain plus compensation is a decision point, not a badge.',
  },
  {
    id: 'exercise_order', bossTheme: 'general',
    prompt: 'If pull-ups are the priority, where should they usually go?',
    options: ['Early enough that fatigue does not sabotage quality.', 'After six biceps finishers.', 'Only when the moon is protein.'],
    answer: 0,
    lesson: 'Priority work generally goes earlier while focus and performance are highest.',
  },
  {
    id: 'frequency_distribution', bossTheme: 'general',
    prompt: 'Why split hard weekly volume across multiple days?',
    options: ['It can improve per-set quality and recovery distribution.', 'Frequency is magic even if total work is nonsense.', 'It guarantees soreness every day, which is the goal.'],
    answer: 0,
    lesson: 'Frequency is mainly a way to distribute quality volume and manage fatigue, not a standalone spell.',
  },
  {
    id: 'load_zone_hypertrophy', bossTheme: 'battle',
    prompt: 'For hypertrophy, what matters most across moderate/light loads?',
    options: ['Hard sets with sufficient effort and appropriate execution.', 'Only exactly 10 reps works.', 'Load does not matter even if sets are effortless.'],
    answer: 0,
    lesson: 'A broad rep range can grow muscle when sets are hard enough and technique targets the tissue.',
  },
  {
    id: 'minimum_effective_dose', bossTheme: 'shop',
    prompt: 'During a busy week, what is the intelligent maintenance strategy?',
    options: ['Use a lower but meaningful dose to preserve momentum.', 'Quit until life is perfect.', 'Do max singles between meetings.'],
    answer: 0,
    lesson: 'Maintenance often requires much less than growth. Keeping the thread alive matters.',
  },
  {
    id: 'progression_double', bossTheme: 'general',
    prompt: 'Double progression means what?',
    options: ['Add reps within a range, then load when the top is achieved with quality.', 'Add load and reps randomly every set.', 'Double the workout because math.'],
    answer: 0,
    lesson: 'Double progression gives structure without forcing load jumps before the reps are owned.',
  },
  {
    id: 'warmup_fatigue_cost', bossTheme: 'boss',
    prompt: 'A lifter does five near-failure warmup sets before work sets. Problem?',
    options: ['Warmups are spending the fatigue budget.', 'Warmups count double for hypertrophy.', 'The boss respects theatrics.'],
    answer: 0,
    lesson: 'Warmups should prepare, not pre-exhaust the work that actually matters.',
  },
  {
    id: 'spotting_safety', bossTheme: 'boss',
    prompt: 'Heavy bench day, no safeties, no spotter. Best decision?',
    options: ['Use safeties/spotter or adjust exercise/load.', 'Max anyway because fear is preworkout.', 'Collars solve everything on bench.'],
    answer: 0,
    lesson: 'Risk management is part of good training. Failure planning matters more when loads can trap you.',
  },
  {
    id: 'eccentric_control', bossTheme: 'battle',
    prompt: 'Which eccentric is usually better for hypertrophy practice?',
    options: ['Controlled enough to maintain position and tension.', 'Dropping the load into the shadow realm.', 'Fifteen seconds every rep no matter what.'],
    answer: 0,
    lesson: 'Control helps keep tension where intended; absurdly slow eccentrics can just reduce loading unnecessarily.',
  },
  {
    id: 'tempo_purpose', bossTheme: 'general',
    prompt: 'When is tempo prescription useful?',
    options: ['When it solves a technical or stimulus problem.', 'Always, because numbers look scientific.', 'Never, because chaos builds character.'],
    answer: 0,
    lesson: 'Tempo is a constraint. Use it to improve execution, not to decorate the spreadsheet.',
  },
  {
    id: 'machine_vs_free', bossTheme: 'shop',
    prompt: 'Machine or free weights for hypertrophy?',
    options: ['Pick the tool that loads the target well and is progressable.', 'Free weights are always superior for every muscle.', 'Machines delete your soul permanently.'],
    answer: 0,
    lesson: 'The body adapts to tension and effort. The implement is subordinate to stimulus quality.',
  },
  {
    id: 'isolation_value', bossTheme: 'battle',
    prompt: 'Why add isolation work if compounds exist?',
    options: ['To target muscles that compounds underdose or fatigue-limit.', 'Because compounds do nothing.', 'To make workouts longer for prestige.'],
    answer: 0,
    lesson: 'Isolation work can improve local stimulus without the systemic fatigue of more heavy compounds.',
  },
  {
    id: 'set_quality', bossTheme: 'general',
    prompt: 'What makes a set “high quality”?',
    options: ['Target muscle loaded, stable technique, appropriate effort, recoverable cost.', 'Any set that hurts emotionally.', 'A set filmed vertically.'],
    answer: 0,
    lesson: 'Quality is about useful stimulus per fatigue and risk, not vibes alone.',
  },
  {
    id: 'junk_volume', bossTheme: 'boss',
    prompt: 'What is junk volume?',
    options: ['Work that adds fatigue without much extra adaptation.', 'Any set over three reps.', 'Exercises without Latin names.'],
    answer: 0,
    lesson: 'More work stops helping when it no longer produces enough marginal stimulus.',
  },
  {
    id: 'deload_not_detain', bossTheme: 'general',
    prompt: 'A good deload should usually do what?',
    options: ['Reduce fatigue while retaining enough movement familiarity.', 'Become a secret max-out week.', 'Erase all training forever.'],
    answer: 0,
    lesson: 'Deloads are bridges between productive waves, not punishment.',
  },
  {
    id: 'sleep_priority', bossTheme: 'boss',
    prompt: 'Sleep is wrecked for several nights. Training adjustment?',
    options: ['Lower expectations/volume/intensity as needed and protect technique.', 'Punish yourself with extra sets.', 'Use caffeine to replace biology completely.'],
    answer: 0,
    lesson: 'Recovery changes readiness. Good programming adapts instead of pretending you are a robot.',
  },
  {
    id: 'protein_distribution', bossTheme: 'shop',
    prompt: 'Protein strategy most defensible for regular lifters?',
    options: ['Adequate daily intake, spread across meals if practical.', 'One tiny protein snack at midnight solves all.', 'Only post-workout timing matters.'],
    answer: 0,
    lesson: 'Daily intake is the foundation; distribution is a useful refinement, not a magic portal.',
  },
  {
    id: 'creatine_basics', bossTheme: 'shop',
    prompt: 'Creatine doctrine?',
    options: ['Consistent daily intake matters more than ritual timing.', 'Only works if dry scooped while yelling.', 'Must be cycled every four days.'],
    answer: 0,
    lesson: 'Creatine is boring in the best way: consistency beats ceremony for most people.',
  },
  {
    id: 'hydration_electrolytes', bossTheme: 'general',
    prompt: 'Long sweaty session, performance fading. Best non-mystical fix?',
    options: ['Fluids plus electrolytes/carbs if duration and sweat justify it.', 'Ignore thirst because discipline.', 'Only sniff ammonia between accessory sets.'],
    answer: 0,
    lesson: 'Hydration and sodium can matter when sweat losses are meaningful.',
  },
  {
    id: 'cutting_training', bossTheme: 'boss',
    prompt: 'During a calorie deficit, best lifting mindset?',
    options: ['Keep tension/intensity while managing volume/recovery.', 'Switch to only high-rep sweat circuits.', 'Expect PRs forever because hunger is magic.'],
    answer: 0,
    lesson: 'In a cut, recovery is tighter. Preserve strength signals without drowning in fatigue.',
  },
  {
    id: 'bulking_rate', bossTheme: 'shop',
    prompt: 'Lean bulk decision?',
    options: ['Use a modest surplus and track trend, not one chaotic weigh-in.', 'Eat randomly and call it intuitive mass.', 'Gain as fast as possible; all weight is muscle.'],
    answer: 0,
    lesson: 'A controlled surplus supports growth while limiting unnecessary fat gain.',
  },
  {
    id: 'tracking_noise', bossTheme: 'general',
    prompt: 'One bad workout appears. What should the logbook goblin do?',
    options: ['Look for trends before overcorrecting.', 'Rewrite the whole program immediately.', 'Assume adaptation has ended.'],
    answer: 0,
    lesson: 'Single-session noise is normal. Trends carry more signal.',
  },
  {
    id: 'exercise_variation_reason', bossTheme: 'general',
    prompt: 'Best reason to rotate an exercise?',
    options: ['Staleness, joint tolerance, target bias, or plateau management.', 'Muscle confusion demands daily chaos.', 'Because the app got bored.'],
    answer: 0,
    lesson: 'Variation should solve a problem or open a new stimulus, not hide lack of progression.',
  },
  {
    id: 'rom_standardization', bossTheme: 'battle',
    prompt: 'Why standardize range of motion in a logbook?',
    options: ['So progress reflects strength/adaptation, not shrinking reps.', 'So reps look uglier.', 'To annoy the mirror shade.'],
    answer: 0,
    lesson: 'Consistent ROM makes performance data meaningful.',
  },
  {
    id: 'partial_rep_tool', bossTheme: 'battle',
    prompt: 'When can partials be useful?',
    options: ['As intentional overload in a productive range, not accidental ego shortening.', 'Whenever full reps get inconvenient.', 'Only if nobody can see.'],
    answer: 0,
    lesson: 'Partials are a tool when programmed. Accidental ROM decay is not the same thing.',
  },
  {
    id: 'cardio_interference', bossTheme: 'general',
    prompt: 'Cardio plus lifting: best interference-management idea?',
    options: ['Dose and schedule cardio so it supports health without crushing priority strength work.', 'Never do cardio under any circumstance.', 'Do maximal intervals before heavy squats always.'],
    answer: 0,
    lesson: 'Concurrent training can work. The dose, modality, and timing decide whether it helps or interferes.',
  },
  {
    id: 'conditioning_health', bossTheme: 'battle',
    prompt: 'Why keep some conditioning even in a strength phase?',
    options: ['Work capacity and health can support better long-term training.', 'Because muscle only grows while gasping.', 'To earn punishment points.'],
    answer: 0,
    lesson: 'Conditioning is not the enemy when dosed intelligently.',
  },
  {
    id: 'technical_consistency', bossTheme: 'boss',
    prompt: 'A strength PR only happened with wildly different technique. Count it how?',
    options: ['Celebrate cautiously, but do not confuse it with clean technical progression.', 'It proves the program is perfect.', 'Change all past logs retroactively.'],
    answer: 0,
    lesson: 'Technique changes can inflate numbers while reducing comparability and increasing risk.',
  },
  {
    id: 'bracing_sequence', bossTheme: 'boss',
    prompt: 'Heavy squat brace sequence?',
    options: ['Set stance, breathe/brace circumferentially, create tension, then descend.', 'Exhale completely and hope.', 'Relax because stiffness blocks vibes.'],
    answer: 0,
    lesson: 'Bracing creates a stable trunk so force goes into the bar instead of chaos.',
  },
  {
    id: 'scap_pull', bossTheme: 'battle',
    prompt: 'Rows keep turning into shruggy biceps chaos. Best cue?',
    options: ['Control scapula/upper arm path and load the target back tissue.', 'Add weight until form surrenders.', 'Only use straps made of moonlight.'],
    answer: 0,
    lesson: 'Targeting back often requires controlling shoulder blade and elbow path, not just moving metal.',
  },
  {
    id: 'squat_depth', bossTheme: 'battle',
    prompt: 'Squat depth for training?',
    options: ['Use consistent, controlled depth appropriate to goals and anatomy.', 'Change depth every rep to keep the body guessing.', 'Only quarter reps count if loud.'],
    answer: 0,
    lesson: 'Depth should be intentional and repeatable. Anatomy and goals matter.',
  },
  {
    id: 'deadlift_fatigue', bossTheme: 'boss',
    prompt: 'Deadlifts are destroying the week. Best programming refinement?',
    options: ['Adjust volume/frequency/variation to keep useful hinge stimulus recoverable.', 'Add more heavy pulls until morale improves.', 'Delete posterior chain training forever.'],
    answer: 0,
    lesson: 'High-fatigue lifts need careful dosing. Stimulus-to-fatigue is the real boss.',
  },
  {
    id: 'accessory_progression', bossTheme: 'shop',
    prompt: 'Accessory lifts should progress how?',
    options: ['Mostly via clean reps/load over time while preserving target tension.', 'Only by maxing singles.', 'By changing names in the logbook.'],
    answer: 0,
    lesson: 'Accessories are still trainable lifts. Progress them without turning them into ego showcases.',
  },
  {
    id: 'rpe_learning', bossTheme: 'general',
    prompt: 'How does a lifter get better at RPE/RIR?',
    options: ['Practice, occasional calibration, and honest post-set reflection.', 'Never compare predictions to reality.', 'Ask the mirror shade for vibes only.'],
    answer: 0,
    lesson: 'Autoregulation is a skill. Calibration makes it sharper.',
  },
  {
    id: 'cluster_sets', bossTheme: 'battle',
    prompt: 'Why use cluster sets?',
    options: ['To preserve rep quality with short intra-set rests for certain strength/power goals.', 'To avoid effort forever.', 'Because crows demanded it.'],
    answer: 0,
    lesson: 'Clusters manipulate fatigue inside a set; they are context-dependent tools.',
  },
  {
    id: 'drop_sets', bossTheme: 'battle',
    prompt: 'Drop sets are best viewed as what?',
    options: ['A time-efficient intensity technique with fatigue costs.', 'Mandatory for every compound lift.', 'A substitute for sleep.'],
    answer: 0,
    lesson: 'Intensity techniques can save time, but they are not free recovery-wise.',
  },
  {
    id: 'myoreps', bossTheme: 'battle',
    prompt: 'Myo-reps/rest-pause mainly do what?',
    options: ['Accumulate hard reps efficiently after an activation set.', 'Magically remove fatigue.', 'Make warmups obsolete.'],
    answer: 0,
    lesson: 'Rest-pause methods can pack hard reps into less time, with careful exercise selection.',
  },
  {
    id: 'failure_isolation', bossTheme: 'battle',
    prompt: 'Where is training to failure usually less risky?',
    options: ['Stable isolation/single-joint work compared with heavy technical compounds.', 'Max deadlifts after midnight.', 'Any lift with enough synth music.'],
    answer: 0,
    lesson: 'Failure has different costs depending on exercise stability, load, and consequence of breakdown.',
  },
  {
    id: 'hypertrophy_strength_split', bossTheme: 'general',
    prompt: 'Hypertrophy and strength training differ mainly how?',
    options: ['Strength needs more specific heavy skill practice; hypertrophy tolerates broader loading.', 'They are unrelated universes.', 'Hypertrophy only happens above 90% 1RM.'],
    answer: 0,
    lesson: 'Muscle size supports strength, but expressing max strength is also a specific skill.',
  },
  {
    id: 'readiness_metrics', bossTheme: 'general',
    prompt: 'Which readiness signal is most actionable in the gym?',
    options: ['Warmup performance and technique quality today.', 'A random influencer quote.', 'Whether the shaker cup hissed.'],
    answer: 0,
    lesson: 'Direct performance/readiness data beats mystical interpretation.',
  },
  {
    id: 'plateau_response', bossTheme: 'boss',
    prompt: 'Three-week plateau on a lift. First intelligent response?',
    options: ['Check sleep, nutrition, technique, volume, effort, and exercise fit before panic.', 'Immediately double all sets.', 'Assume genetics filed a lawsuit.'],
    answer: 0,
    lesson: 'Plateaus have causes. Diagnose before adding chaos.',
  },
  {
    id: 'priority_tradeoff', bossTheme: 'boss',
    prompt: 'You want everything to improve at once. Advanced programming reality?',
    options: ['Prioritization matters because recovery and attention are finite.', 'All goals peak simultaneously if the playlist is right.', 'Never specialize.'],
    answer: 0,
    lesson: 'Blocks exist because adaptation resources are limited. Choose what leads.',
  },
  {
    id: 'technique_video', bossTheme: 'general',
    prompt: 'Why film occasional sets?',
    options: ['To compare technique against what the set felt like.', 'To prove everyone else is wrong.', 'To summon influencer phantom.'],
    answer: 0,
    lesson: 'Video is feedback. Perception and execution often diverge under load.',
  },
  {
    id: 'program_adherence', bossTheme: 'shop',
    prompt: 'The “optimal” plan is hated and skipped. Better design?',
    options: ['Slightly less theoretical, far more adherent and progressive.', 'Keep it hated; suffering is adherence.', 'No plan, only vibes.'],
    answer: 0,
    lesson: 'A good program has to be executable by the actual human using it.',
  },
  {
    id: 'environment_constraints', bossTheme: 'general',
    prompt: 'Gym is packed and your planned station is taken. Best move?',
    options: ['Use an equivalent pattern/target substitution and keep the session moving.', 'Wait 45 minutes guarding the bench.', 'Abandon adaptation.'],
    answer: 0,
    lesson: 'Good training has principles beneath exercise names. Substitute intelligently.',
  },
  {
    id: 'stimulus_check', bossTheme: 'boss',
    prompt: 'After a set, best reflective question?',
    options: ['Did the target tissue do hard, trackable work at an acceptable cost?', 'Did strangers fear me?', 'Was the pain cinematic?'],
    answer: 0,
    lesson: 'The best lifters keep asking whether the set did the job it was hired to do.',
  },

];

export function doctrineForSeed(seed: number, avoidIds: string[] = []): DoctrineQuestion {
  const unused = DOCTRINE_QUESTIONS.filter(q => !avoidIds.includes(q.id));
  const pool = unused.length ? unused : DOCTRINE_QUESTIONS;
  return pool[Math.abs(Math.floor(seed)) % pool.length];
}

