import { DungeonEnemy, DungeonRelic, DungeonRoomType } from './types';

export const DUNGEON_TITLES = [
  'Squire of Suspicious Pump', 'Cable Goblin Negotiator', 'Neon Knee Apostle', 'Dungeon Spotter',
  'Whey Prophet', 'Barbell Cryptid', 'Cardio Heretic', 'Lactic Acid Warlock',
  'Rack Goblin Diplomat', 'Forbidden Bulk Scholar', 'Glute Bridge Ronin', 'Shrine of DOMS Custodian',
  'Chalk Cloud Warden', 'Protein Moon Howler', 'Smith Machine Exorcist', 'Plate Tree Cartographer',
  'Biceps Necromancer', 'Swolecrypt Tax Evader', 'Final Set Witness', 'Lord of the Purple Foam Roller',
  'Hypertrophy Gremlin King', 'The Rep Counter Who Knows Too Much',
];

export const MONSTERS: DungeonEnemy[] = [
  ['brogoblin','BROGOBLIN',18,5,0,7,8,'💪','pink','DO YOU EVEN CRAWL?'],
  ['protein_mimic','PROTEIN MIMIC',20,4,2,8,10,'🥤','cyan','IT WAS NEVER VANILLA.'],
  ['cardio_wraith','CARDIO WRAITH',16,7,0,9,9,'👻','violet','ZONE TWO FOREVER.'],
  ['leg_day_larva','LEG DAY LARVA',22,5,1,8,7,'🦵','green','NO STAIRS REMAIN.'],
  ['bench_banshee','BENCH BANSHEE',19,6,1,9,8,'🏋️','pink','ARCH HARDER.'],
  ['curl_imp','CURL IMP',15,5,0,6,12,'😈','orange','HALF REP? HALF SOUL.'],
  ['chalk_sprite','CHALK SPRITE',14,4,3,7,6,'☁️','cyan','GRIP THE VOID.'],
  ['foam_roller_slug','FOAM ROLLER SLUG',26,3,4,8,5,'🌀','violet','THIS WILL BE TENDER.'],
  ['preworkout_pixie','PREWORKOUT PIXIE',17,8,0,10,13,'⚡','yellow','TINGLE ASCENSION.'],
  ['plate_tree_troll','PLATE TREE TROLL',28,6,2,11,11,'🪨','green','RERACK OR PERISH.'],
  ['elliptical_ghost','ELLIPTICAL GHOST',18,5,2,8,9,'🛸','cyan','LOW IMPACT, HIGH CURSE.'],
  ['smith_machine_demon','SMITH MACHINE DEMON',24,7,2,12,12,'⛓️','red','FIXED PATH TO DOOM.'],
  ['lat_pulldown_leech','LAT PULLDOWN LEECH',20,6,1,9,9,'🪱','green','SCAPULA OFFERING.'],
  ['deadlift_dreg','DEADLIFT DREG',25,8,1,13,12,'🪦','red','BRACE BEFORE ERASURE.'],
  ['treadmill_lichling','TREADMILL LICHling'.toUpperCase(),21,7,0,12,10,'💀','violet','SPEED 12, INCLINE 12.'],
  ['cable_cultist','CABLE CULTIST',19,6,2,10,14,'🧙','pink','TENSION IS RELIGION.'],
  ['sauna_serpent','SAUNA SERPENT',23,6,1,10,11,'🐍','orange','HYDRATE OR HALLUCINATE.'],
  ['locker_mimic','LOCKER MIMIC',20,6,3,11,16,'🧰','cyan','YOUR COMBO IS FEAR.'],
  ['spotter_zombie','SPOTTER ZOMBIE',27,5,2,10,8,'🧟','green','ALL YOU, BRO.'],
  ['trap_bar_bat','TRAP BAR BAT',18,8,1,11,13,'🦇','red','HEXAGONAL HUNGER.'],
  ['ab_wheel_gremlin','AB WHEEL GREMLIN',17,7,1,10,9,'🛞','yellow','ROLL OUT, NEVER RETURN.'],
  ['kettlebell_kobold','KETTLEBELL KOBOLD',22,7,2,12,12,'🔔','orange','SWING INTO MADNESS.'],
  ['superset_specter','SUPERSET SPECTER',21,8,0,12,13,'🧬','violet','REST IS ILLEGAL.'],
  ['macro_rat','MACRO RAT',16,5,1,8,15,'🐀','green','COUNT ME, COWARD.'],
  ['influencer_phantom','INFLUENCER PHANTOM',19,7,0,10,18,'📱','pink','LIKE, SAVE, SUFFER.'],
  ['airbike_abomination','AIRBIKE ABOMINATION',30,8,1,14,10,'🌪️','red','CALORIES SCREAM.'],
  ['creatine_crab','CREATINE CRAB',23,6,3,11,12,'🦀','cyan','LOAD PHASE CLAWS.'],
  ['squat_rack_jester','SQUAT RACK JESTER',24,7,2,13,13,'🃏','yellow','THE RACK LAUGHS.'],
  ['mirror_shade','MIRROR SHADE',20,8,1,12,14,'🪞','violet','YOUR FORM WATCHES BACK.'],
  ['rowing_goblin','ROWING GOBLIN',21,7,2,11,11,'🚣','green','PULL THE SWAMP.'],
  ['burpee_bug','BURPEE BUG',18,9,0,12,12,'🪲','red','DOWN. UP. DOOM.'],
  ['incline_basilisk','INCLINE BASILISK',26,8,2,14,15,'🦎','pink','LOOK UPON UPPER CHEST.'],
  ['tricep_toad','TRICEP TOAD',19,6,2,10,10,'🐸','green','ELBOWS IN, SOUL OUT.'],
  ['hamstring_harpy','HAMSTRING HARPY',22,9,0,13,12,'🪽','orange','ECCENTRIC SHRIEK.'],
  ['deload_doppel','DELOAD DOPPELGANGER',21,5,4,12,9,'👥','cyan','LESS IS MORE, FOOL.'],
  ['caffeine_cyclops','CAFFEINE CYCLOPS',24,9,1,14,16,'👁️','yellow','400MG OF DESTINY.'],
  ['gym_bag_ooze','GYM BAG OOZE',28,6,3,13,14,'🫧','green','WASH ME NEVER.'],
  ['pec_deck_poltergeist','PEC DECK POLTERGEIST',23,8,2,13,13,'🦾','violet','SQUEEZE THE ETHER.'],
  ['stairmaster_siren','STAIRMASTER SIREN',25,8,1,14,15,'🧜','cyan','CLIMB FOREVER.'],
  ['jump_rope_jackal','JUMP ROPE JACKAL',18,10,0,13,14,'🐺','orange','DOUBLE UNDERWORLD.'],
  ['hydration_homunculus','HYDRATION HOMUNCULUS',22,6,4,12,17,'💧','cyan','ELECTROLYTE OR DIE.'],
  ['meal_prep_mummy','MEAL PREP MUMMY',27,7,2,14,15,'🍱','yellow','SUNDAY NEVER ENDS.'],

  ['tempo_tax_collector','TEMPO TAX COLLECTOR',24,9,2,15,18,'🧾','cyan','THREE SECONDS DOWN, PAY UP.'],
  ['range_of_motion_ronin','RANGE OF MOTION RONIN',27,8,3,16,16,'🥷','pink','DEPTH IS HONOR.'],
  ['eccentric_egg','ECCENTRIC EGG',18,11,1,14,20,'🥚','yellow','SLOWLY I CRACK.'],
  ['mobility_mothman','MOBILITY MOTHMAN',23,8,4,15,17,'🦋','violet','YOUR ANKLES HAVE SECRETS.'],
  ['grip_ghoul','GRIP GHOUL',21,10,2,15,19,'🖐️','green','STRAPS? IN THIS ECONOMY?'],
  ['pumpkin_spice_spotter','PUMPKIN SPICE SPOTTER',26,7,4,16,21,'🎃','orange','SEASONAL BULK ENERGY.'],
  ['periodization_poltergeist','PERIODIZATION POLTERGEIST',25,9,3,17,22,'📈','cyan','BLOCKS WITHIN BLOCKS.'],
  ['warmup_wendigo','WARMUP WENDIGO',22,10,2,15,17,'🦌','red','RAMP SETS OR REGRET.'],
  ['volume_vulture','VOLUME VULTURE',28,9,2,18,20,'🦅','violet','JUNK SETS TASTE GOOD.'],
  ['rir_revenant','RIR REVENANT',24,10,3,18,22,'👻','green','YOU HAD THREE LEFT.'],
  ['deload_druid','DELOAD DRUID',30,6,6,17,16,'🧝','green','RECOVER, THEN ASCEND.'],
  ['prehab_piranha','PREHAB PIRANHA',20,11,2,16,20,'🐟','cyan','SMALL PAIN, BIG TEETH.'],
  ['supinated_skeleton','SUPINATED SKELETON',21,10,3,16,18,'💀','yellow','PALMS UP, SOULS OUT.'],
  ['pronated_pharaoh','PRONATED PHARAOH',26,9,4,17,21,'🪬','orange','OVERHAND CURSE.'],
  ['neutral_grip_gnome','NEUTRAL GRIP GNOME',24,8,5,17,19,'🧙','green','WRISTS REMAIN DIPLOMATIC.'],
  ['velocity_loss_vampire','VELOCITY LOSS VAMPIRE',25,11,2,19,24,'🧛','red','YOUR BAR SPEED BLEEDS.'],
  ['cluster_set_crow','CLUSTER SET CROW',23,10,3,18,23,'🐦‍⬛','violet','REST INSIDE THE SET.'],
  ['drop_set_djinn','DROP SET DJINN',22,12,1,19,25,'🧞','pink','REMOVE WEIGHT, ADD CHAOS.'],
  ['myorep_mushroom','MYO-REP MUSHROOM',19,12,2,18,24,'🍄','cyan','TINY RESTS, HUGE SPORES.'],
  ['stretch_mediated_mantis','STRETCH-MEDIATED MANTIS',27,11,3,20,25,'🦗','green','LONG MUSCLE LENGTH, LONG NIGHT.'],
  ['shortened_range_shade','SHORTENED RANGE SHADE',20,13,1,17,22,'🌘','violet','LOCKOUT LIES.'],
  ['bracing_basilisk','BRACING BASILISK',29,10,4,20,24,'🐍','red','BREATHE INTO THE BELT.'],
  ['valgus_goblin','VALGUS GOBLIN',23,12,2,18,21,'🦵','pink','KNEES CAVE, CAVES KNEEL.'],
  ['scapula_sphinx','SCAPULA SPHINX',28,9,5,20,25,'🦁','yellow','ANSWER WITH YOUR SHOULDER BLADES.'],
  ['sleep_debt_specter','SLEEP DEBT SPECTER',26,11,3,20,26,'🛌','cyan','RECOVERY COMES DUE.'],
  ['hydration_hag','HYDRATION HAG',24,10,4,18,23,'🧙‍♀️','green','SALT THE WATER.'],
  ['fiber_type_fiend','FIBER TYPE FIEND',25,11,3,21,25,'🧬','red','FAST TWITCH, SLOW DOOM.'],
  ['mechanical_tension_titanling','MECHANICAL TENSION TITANLING',32,11,5,23,28,'🗿','orange','LOAD MEANINGFULLY.'],
  ['metabolite_mermaid','METABOLITE MERMAID',22,13,2,20,27,'🧜‍♀️','cyan','THE BURN IS NOT THE WHOLE SPELL.'],
  ['stimulus_fatigue_ferret','STIMULUS-FATIGUE FERRET',21,12,3,20,26,'🦦','violet','WHY SO TIRED FOR SO LITTLE?'],
  ['adaptive_resistance_imp','ADAPTIVE RESISTANCE IMP',24,12,3,21,29,'😈','pink','I ADAPT TO YOUR ADAPTATION.'],
  ['overreach_ogre','OVERREACH OGRE',34,12,4,24,31,'👹','red','TEMPORARY SUFFERING, MAYBE.'],
  ['peaking_peacock','PEAKING PEACOCK',25,13,3,22,30,'🦚','yellow','TAPER AND BEHOLD.'],
  ['plateau_pirate','PLATEAU PIRATE',30,11,5,23,28,'🏴‍☠️','cyan','NO PROGRESS, ALL PLUNDER.'],
  ['accessory_ankylosaur','ACCESSORY ANKYLOSAUR',31,10,6,22,27,'🦕','green','SMALL LIFTS, HEAVY TAIL.'],
  ['isometric_ichor','ISOMETRIC ICHOR',26,12,5,22,29,'🧫','violet','HOLD STILL AND PANIC.'],
  ['paused_rep_puppet','PAUSED REP PUPPET',24,13,3,22,30,'🧸','pink','NO BOUNCE, ONLY TRUTH.'],
  ['amrap_angel','AMRAP ANGEL',28,13,4,24,32,'👼','yellow','AS MANY REPENTANCES AS POSSIBLE.'],
  ['e1rm_eldritch','E1RM ELDRITCH',27,14,3,24,33,'🧮','cyan','ESTIMATE THE UNKNOWABLE.'],
  ['logbook_leviathan','LOGBOOK LEVIATHAN',36,12,5,26,35,'🐋','green','I REMEMBER EVERY SET.'],
].map(([id, name, hp, attack, defense, xp, coins, sprite, palette, taunt]) => ({
  id, name, hp, attack, defense, xp, coins, sprite, palette, taunt,
})) as DungeonEnemy[];

export const BOSSES: DungeonEnemy[] = [
  ['leg_day_lich','LEG DAY LICH',46,10,3,30,35,'🦵','red','THOU SKIPPED ME.'],
  ['preworkout_warlock','PREWORKOUT WARLOCK',42,12,2,32,40,'🧙','yellow','DRY SCOOP THE ABYSS.'],
  ['the_incline_beast','THE INCLINE BEAST',50,11,4,34,42,'🐉','pink','UPPER CHEST JUDGMENT.'],
  ['king_brogoblin','KING BROGOBLIN',54,10,5,36,45,'👑','green','CROWNED IN SWEAT.'],
  ['protein_moon','THE PROTEIN MOON',48,12,3,35,50,'🌕','cyan','ALL MACROS ORBIT ME.'],
  ['barbell_minotaur','BARBELL MINOTAUR',58,13,4,40,55,'🐂','red','NO EXIT FROM THE RACK.'],
  ['cardio_reaper','CARDIO REAPER',44,15,1,38,48,'☠️','violet','YOUR HEART RATE IS MINE.'],
  ['sauna_oracle','SAUNA ORACLE',52,11,5,39,46,'♨️','orange','STEAM TELLS TERRIBLE TRUTHS.'],
  ['glitch_spotter','GLITCH SPOTTER 404',49,14,2,42,60,'📟','cyan','FORM CHECK FAILED.'],
  ['doms_dragon','DOMS DRAGON',60,14,4,45,65,'🐲','pink','TOMORROW BURNS.'],
  ['swoldemort','SWOLDEMORT',64,15,5,50,75,'🦹','violet','THE BOY WHO LIFTED.'],
  ['final_set_seraph','FINAL SET SERAPH',70,16,6,60,90,'👼','yellow','ONE MORE REP, MORTAL.'],

  ['hypertrophy_hydra','HYPERTROPHY HYDRA',74,17,6,65,95,'🐉','green','CUT ONE SET, TWO MORE APPEAR.'],
  ['mesocycle_magus','MESOCYCLE MAGUS',76,18,5,68,100,'🧙','cyan','WEEK FOUR COMES FOR YOU.'],
  ['rir_judge','THE RIR JUDGE',72,19,4,70,105,'⚖️','yellow','STATE YOUR REPS IN RESERVE.'],
  ['volume_overlord','VOLUME OVERLORD',84,17,7,76,110,'👑','red','MORE IS MORE UNTIL IT IS NOT.'],
  ['technique_terminator','TECHNIQUE TERMINATOR',80,20,6,78,115,'🤖','violet','NO REP DETECTED.'],
  ['recovery_kraken','RECOVERY KRAKEN',88,18,8,82,120,'🐙','cyan','SLEEP OR SINK.'],
  ['specificity_samurai','SPECIFICITY SAMURAI',82,21,5,84,125,'🥷','pink','PRACTICE THE BLADE YOU WIELD.'],
  ['long_length_leviathan','LONG-LENGTH LEVIATHAN',90,19,7,88,130,'🐋','green','STRETCH UNDER LOAD.'],
  ['autoregulation_archon','AUTOREGULATION ARCHON',86,20,6,90,135,'👁️','yellow','READINESS IS LAW.'],
  ['plateau_pharaoh','PLATEAU PHARAOH',94,21,8,96,145,'🪬','orange','PROGRESS IS SEALED.'],
  ['evidence_emperor','EVIDENCE EMPEROR',100,22,8,105,160,'📚','cyan','CITE YOUR SPELLS.'],
  ['the_last_deload','THE LAST DELOAD',112,23,9,125,200,'🪦','violet','REST BEFORE I REST YOU.'],
].map(([id, name, hp, attack, defense, xp, coins, sprite, palette, taunt]) => ({
  id, name, hp, attack, defense, xp, coins, sprite, palette, taunt,
})) as DungeonEnemy[];

export const RELICS: DungeonRelic[] = [
  ['cursed_wraps','CURSED KNEE WRAPS','armor','+2 defense. Whisper compliments to your patellas.',0,2,0,0,0,0,'🩹'],
  ['ghost_pre','GHOST PREWORKOUT','snack','Heal 12 HP and gain +1 crit. You can hear colors.',0,0,0,1,0,12,'⚗️'],
  ['bad_barbell','BARBELL OF BAD DECISIONS','weapon','+4 attack. Absolutely not calibrated.',4,0,0,0,0,0,'🏋️'],
  ['foam_crown','FOAM ROLLER CROWN','charm','+8 max HP. Nobility through soreness.',0,0,8,0,0,0,'👑'],
  ['macro_abacus','MACRO ABACUS','charm','Gain 25 coins. Math goblins respect you.',0,0,0,0,25,0,'🧮'],
  ['spotter_contract','UNDEAD SPOTTER CONTRACT','armor','+1 defense, +3 max HP. All you, bro.',0,1,3,0,0,0,'📜'],
  ['trap_hex','TRAP BAR HEX','weapon','+2 attack, +2 defense. Geometry gets swole.',2,2,0,0,0,0,'⬡'],
  ['sweat_vial','VIAL OF ANCESTRAL SWEAT','snack','Heal 18 HP. Do not ask whose.',0,0,0,0,0,18,'🧪'],
  ['neon_belt','NEON LIFTING BELT','armor','+3 defense. Buckle the timeline.',0,3,0,0,0,0,'🦺'],
  ['mirror_shard','MIRROR SHARD OF FORM','charm','+2 crit. The mirror finally helps.',0,0,0,2,0,0,'🔹'],
  ['dumbbell_familiar','DUMBBELL FAMILIAR','weapon','+3 attack. It follows. It judges.',3,0,0,0,0,0,'🐾'],
  ['protein_orb','ORPHANED PROTEIN ORB','snack','Heal 10 HP, gain 10 coins.',0,0,0,0,10,10,'🟣'],
  ['glute_bridge','GLUTE BRIDGE PASSPORT','charm','+6 max HP. Diplomatic immunity from weak hinges.',0,0,6,0,0,0,'🌉'],
  ['chalk_halo','CHALK HALO','charm','+1 attack, +1 defense, +1 crit.',1,1,0,1,0,0,'⭕'],
  ['forbidden_shaker','FORBIDDEN SHAKER CUP','glitch','+5 attack, lose 6 HP. It is alive.',5,0,0,0,0,-6,'🥛'],
  ['sauna_key','SAUNA KEY OF PROPHECY','charm','+2 defense, +12 coins.',0,2,0,0,12,0,'🗝️'],
  ['beast_tape','INCLINE BEAST TAPE','weapon','+5 attack. Sticky with myth.',5,0,0,0,0,0,'🧷'],
  ['cardio_coupon','CARDIO COUPON','curse','+30 coins, -2 attack. Expiration: never.',-2,0,0,0,30,0,'🎟️'],
  ['hydration_gem','HYDRATION GEM','snack','Heal 22 HP. Electrolyte gemstone.',0,0,0,0,0,22,'💎'],
  ['brogoblin_tooth','BROGOBLIN TOOTH','weapon','+2 attack, +10 coins. Grossly lucky.',2,0,0,0,10,0,'🦷'],
  ['tempo_metronome','ECCENTRIC METRONOME','charm','+2 defense, +2 crit. Slow descent into madness.',0,2,0,2,0,0,'🎚️'],
  ['leg_press_throne','LEG PRESS THRONE','armor','+10 max HP, +1 defense.',0,1,10,0,0,0,'🪑'],
  ['deload_feather','DELOAD FEATHER','snack','Heal 30 HP, -1 attack. Rest is technology.',-1,0,0,0,0,30,'🪶'],
  ['pump_lantern','PUMP LANTERN','charm','+1 attack, +8 max HP.',1,0,8,0,0,0,'🏮'],
  ['mystery_plate','MYSTERY 35LB PLATE','glitch','+3 attack, +3 defense, but reality hates it.',3,3,0,0,0,0,'🛸'],
  ['hamstring_harp','HAMSTRING HARPY HARP','weapon','+4 attack, +1 crit.',4,0,0,1,0,0,'🎻'],
  ['locker_relic','LOCKER 13 RELIC','charm','+13 coins, +3 max HP.',0,0,3,0,13,0,'🧰'],
  ['stair_sigil','STAIRMASTER SIGIL','armor','+2 defense, +5 max HP.',0,2,5,0,0,0,'🪜'],
  ['curl_scroll','SCROLL OF HONEST CURLS','weapon','+3 attack. Full range or doom.',3,0,0,0,0,0,'📃'],
  ['shrug_shroud','TRAP SHRUG SHROUD','armor','+4 defense, -1 crit.',0,4,0,-1,0,0,'🧥'],
  ['meal_prep_idol','MEAL PREP IDOL','charm','+20 coins. Smells like Sunday.',0,0,0,0,20,0,'🍱'],
  ['rpe_oracle','RPE ORACLE EYE','charm','+3 crit. It knows you had two reps left.',0,0,0,3,0,0,'👁️'],
  ['cable_scepter','CABLE CULT SCEPTER','weapon','+4 attack, +1 defense.',4,1,0,0,0,0,'🪄'],
  ['ab_wheel','AB WHEEL OF RETURNING','weapon','+2 attack, +2 crit.',2,0,0,2,0,0,'🛞'],
  ['bench_pin','BENCH PIN OF MERCY','armor','+3 defense. Finally, safeties.',0,3,0,0,0,0,'📍'],
  ['creatine_pearl','CREATINE PEARL','snack','+6 max HP, heal 12 HP.',0,0,6,0,0,12,'⚪'],
  ['airbike_fan','AIRBIKE FAN BLADE','weapon','+6 attack, -1 defense.',6,-1,0,0,0,0,'🌪️'],
  ['jump_rope','JUMP ROPE OF BAD PORTALS','glitch','+4 crit, lose 4 max HP.',0,0,-4,4,0,0,'➰'],
  ['row_handle','ROWER HANDLE FROM BELOW','weapon','+3 attack, +8 coins.',3,0,0,0,8,0,'🚣'],
  ['wrist_wraps','WRIST WRAPS OF DENIAL','armor','+2 defense, +2 attack.',2,2,0,0,0,0,'🧤'],
  ['moon_scoop','MOON SCOOP','snack','Heal to max HP once. Lunar whey.',0,0,0,0,0,999,'🌙'],
  ['glitch_token','404 REP TOKEN','glitch','Random power hums: +2 all stats-ish.',2,2,4,1,4,4,'🕹️'],
  ['towel_cape','TOWEL CAPE','armor','+5 max HP, +1 defense. Heroic mildew.',0,1,5,0,0,0,'🧣'],
  ['smith_key','SMITH MACHINE KEY','weapon','+5 attack. Unlocks fixed-path violence.',5,0,0,0,0,0,'🔑'],
  ['superset_clock','SUPERSET CLOCK','charm','+2 attack, +2 crit. Rest timer screams.',2,0,0,2,0,0,'⏱️'],
  ['basilisk_scale','INCLINE BASILISK SCALE','armor','+3 defense, +3 max HP.',0,3,3,0,0,0,'🐉'],
  ['doms_rose','DOMS ROSE','curse','+7 max HP, lose 7 HP now.',0,0,7,0,0,-7,'🥀'],
  ['coin_carb','CARB COIN','snack','+35 coins. Delicious legal tender.',0,0,0,0,35,0,'🪙'],
  ['seraph_pin','FINAL SET SERAPH PIN','charm','+4 attack, +4 defense, +4 crit.',4,4,0,4,0,0,'✨'],
  ['swoldemort_nose','SWOLDEMORT NOSELESS MASK','glitch','+8 attack, -8 max HP. Terrible idea.',8,0,-8,0,0,0,'🎭'],
  ['purple_foam','PURPLE FOAM ROLLER','snack','Heal 16 HP, +1 defense.',0,1,0,0,0,16,'🟪'],
  ['bcaas','ANCIENT BCAAS','snack','Heal 8 HP, +2 attack. Possibly just juice.',2,0,0,0,0,8,'🧃'],
  ['lat_wings','LAT WINGS','charm','+3 attack, +3 max HP. Fly wide.',3,0,3,0,0,0,'🪽'],
  ['deadlift_bell','GRAVE BELL OF DEADLIFTS','weapon','+7 attack, -2 defense.',7,-2,0,0,0,0,'🔔'],
].map(([id, name, kind, description, attack, defense, maxHp, crit, coins, heal, sprite]) => ({
  id, name, kind, description, attack, defense, maxHp, crit, coins, heal, sprite,
})) as DungeonRelic[];

export const ROOM_EVENTS: { id: string; type: DungeonRoomType; title: string; text: string; sprite: string }[] = [
  ['neon_gate','fight','Neon Gate','The cable stack exhales fog. Something flexes in the dark.','🚪'],
  ['lost_locker','loot','Lost Locker','A locker hums with protein-scented electricity.','🧰'],
  ['shrine_doms','shrine','Shrine of DOMS','A velvet altar asks for soreness as payment.','🛐'],
  ['wet_floor','trap','Wet Floor Sigil','The caution sign has too many eyes.','⚠️'],
  ['merchant_rat','merchant','Macro Rat Merchant','A rat in a visor sells illegal carbohydrates.','🐀'],
  ['stretch_zone','rest','Stretch Zone','A foam roller rolls toward you like a loyal dog.','🌀'],
  ['broken_timer','glitch','Broken Rest Timer','88:88 blinks. Time has entered failure.','📟'],
  ['plate_rain','loot','Plate Rain','Nickels and dimes fall from the ceiling.','🪙'],
  ['sauna_mist','shrine','Sauna Mist Oracle','Steam writes your PRs backward.','♨️'],
  ['mirror_room','trap','Mirror Room','Every reflection has better form.','🪞'],
  ['deadlift_hall','fight','Deadlift Hall','The floor demands a sacrifice from your spine.','🪦'],
  ['vending_moon','merchant','Vending Moon','A lunar vending machine accepts sweat only.','🌕'],
  ['glute_bridge','rest','Glute Bridge','A bridge made of neon hamstrings restores courage.','🌉'],
  ['bench_crypt','fight','Bench Crypt','A barbell lowers itself into the grave.','⚰️'],
  ['protein_fountain','shrine','Protein Fountain','Thick liquid glows. The scoop is missing.','⛲'],
  ['cardio_chasm','trap','Cardio Chasm','A treadmill belt stretches across infinity.','🕳️'],
  ['rack_market','merchant','Rack Market','Goblins haggle over fractional plates.','🏪'],
  ['chalk_storm','glitch','Chalk Storm','White static coats your soul.','☁️'],
  ['hamstring_nest','fight','Hamstring Nest','A distant stretch becomes a shriek.','🪹'],
  ['coin_sauna','loot','Coin Sauna','Hot coins hiss in a cedar bucket.','🪣'],
  ['ab_wheel_pit','trap','Ab Wheel Pit','The pit rolls away from you.','🛞'],
  ['hydration_pool','rest','Hydration Pool','Electrolytes ripple like forbidden stars.','💧'],
  ['ego_platform','shrine','Ego Platform','A glowing platform asks how much you bench.','📣'],
  ['influencer_wall','glitch','Influencer Wall','Every brick is filming you vertically.','📱'],
  ['leg_press_cathedral','fight','Leg Press Cathedral','The throne wants 18 plates per side.','⛪'],
  ['carb_cache','loot','Carb Cache','A treasure chest full of waffles blinks awake.','🧇'],
  ['cable_choir','fight','Cable Choir','Pulleys chant in minor thirds.','🎼'],
  ['deload_garden','rest','Deload Garden','Tiny dumbbells bloom at half intensity.','🌸'],
  ['forbidden_pr','shrine','Forbidden PR Shrine','The altar promises numbers with consequences.','🏆'],
  ['smith_maze','glitch','Smith Maze','Every path is fixed and none are correct.','⛓️'],
  ['final_set_door','boss','Final Set Door','A golden door whispers: one more.','🚪'],
  ['bcaas_swamp','trap','BCAA Swamp','It is mostly blue. Probably safe.','🧃'],
  ['rower_river','fight','Rower River','A goblin rows upstream inside your mind.','🚣'],
  ['locker_oracle','loot','Locker Oracle','The combo is 6-6-6 reps.','🔐'],
  ['burpee_field','trap','Burpee Field','The ground itself says DOWN.','🌾'],
  ['moon_platform','boss','Protein Moon Platform','The moon descends, swole and judgmental.','🌕'],
].map(([id, type, title, text, sprite]) => ({ id, type, title, text, sprite })) as { id: string; type: DungeonRoomType; title: string; text: string; sprite: string }[];

export function pickBySeed<T>(items: T[], seed: number): T {
  return items[Math.abs(Math.floor(seed)) % items.length];
}

